[package]
name = "pass-gen-mobile"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "pass_gen_mobile"
crate-type = ["cdylib", "staticlib", "lib"]

[dependencies]
getrandom = "0.4"
gpui-mobile = { git = "https://github.com/itsbalamurali/gpui-mobile", rev = "c7cab3a43970bd5f1e05d907695404ed73fcdc95" }
gpui = { git = "https://github.com/zed-industries/zed", rev = "5688167d224b5eca54875d49afb8bfd73a07915a", package = "gpui", default-features = false }
log = "0.4"

[target.'cfg(target_os = "android")'.dependencies]
android-activity = { version = "0.6", features = ["native-activity"] }
android_logger = "0.15"
jni = "0.22"

[patch.crates-io]
stacksafe-macro = { path = "vendor/stacksafe-macro" }

[package.metadata.android]
package = "dev.keyforge.mobile"
apk_name = "pass-gen-1.0"

[package.metadata.android.sdk]
min_sdk_version = 26
target_sdk_version = 37

[package.metadata.android.application]
label = "Pass Gen 1.0"
